FROM jenkins/jenkins

USER root

RUN apt-get update -y && \
    apt-get install -y python3 && \
    apt-get install -y python3-distutils && \
    apt-get install -y python3-apt && \
    curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    pip3 install ansible --upgrade

USER jenkins

